"Create Set id: 10, 02/09/2019."
task createset10: :environment do
  log = ActiveSupport::Logger.new("log/create_set_10.log")
  start_time = Time.now
  puts "**************************"
  puts "Create Set and Cards id 3:VS Code Power Shortcuts"
  puts "**************************"
  # constants
  # find and kill old cluster cards
  # and the cluster's cards. get ready to update scoreclusters if there is a cluster1
  cheatsheet1 = Cheatsheet.where(display_name: "VS Code Power Shortcuts").first
  if cheatsheet1
    old_cheatsheet_id = cheatsheet1.id
    puts "old cheatsheet id was: #{old_cheatsheet_id}"
    cheatsheet1.destroy
    # temp_scoreclusters = Scorecluster.where(cluster_id: old_cluster_id)
    # temp_scorecards = Scorecard.where(cluster_id: old_cluster_id)
  end
  # create new cluster, and add cards back to it.
  test_cheatsheet = Cheatsheet.create!(display_name: "VS Code Power Shortcuts", image: "vscode-dss.png",
                                 description: "These are the indispensable shortcuts that will start you on your journey mastering Microsoft's Visual Studio Code.",
                                 level: "Basic", card_count: -1, topic: "VSCode", os: "")

  # if temp_scoreclusters
  #   puts "Affected Scoreclusters: #{temp_scoreclusters.count}"
  #   puts "Scoreclusters were found, so update from #{old_cluster_id} to #{test_cluster.id}"
  #   temp_scoreclusters.update_all(cluster_id: test_cluster.id)
  # end

  # if temp_scorecards
  #   puts "Affected Scorecards: #{temp_scorecards.count}"
  #   puts "Scorecards were found, so update from #{old_cluster_id} to #{test_cluster.id}"
  #   temp_scorecards.update_all(cluster_id: test_cluster.id)
  # end

  # change cluster_id: x to cluster_id: test_cluster.id
  Card.create!([
    {question: "How do I see all the Visual Studio Keyboard Shortcuts?", answer: "Open the Keyboard Shortcuts", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_cmd, key_k, then, key_left_cmd, key_s", description: "Opens the keybindings file, where you can find, and change, any keyboard shortcut. Be cautious about changing the keyboard shortcut for a given command one day, then trying to remember your new shortcut the next.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine having to kick a giant sheep to open your computer.", gif_url: nil, b_color: nil},
    {question: "How do I instantly reformat a block of code?", answer: "If, and unfortunately its a big if, you have properly configured VS Code with the right extensions, Command-K,Command-F, will reformat a block.", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_cmd, key_k, then, key_left_cmd, key_f", description: "VS Code can do much of the routine formatting of your files. But you need to set it up correctly. Try Googling \"VS Code linting for x\" where x is the language you write in most.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine kicking over a fiery bundle of printouts of your current project to save it.", gif_url: nil, b_color: nil},
    {question: "How do I run any command by just typing a few of its letters?", answer: "Open the Command Palette, then type a few letters from the command you want.", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_shift, key_left_cmd, key_p", description: "Opens the Command Palette", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Image getting an enormous paint palette with hundreds of your favorite colors to appear whenever you command it.", gif_url: nil, b_color: nil},
    {question: "How do I move a line of code up or down?", answer: "Put the cursor in the line, hit option up arrow/down arrow", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_alt, key_down, or key_up", description: "Option up/down arrow can work for a single line, or a block of text.Note that you will probably have to reformat the selection with Command-K,Command-F", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine tying a block of optional code to an arrow you shoot into the sky.", gif_url: nil, b_color: nil},
    {question: "How do I quickly jump to the matching bracket of where I am?", answer: "Shift-Command-backslash will jump the cursor to the matching bracket. Hitting this combo repeatedly will jump you between the starting and ending brackets.", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_shift, key_left_command, key_pipe", description: "Very handy when you need to move through code, a function at a time.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine commanding the pipe character to shift into a bracket.", gif_url: nil, b_color: nil},
    {question: "How do I copy a line of code?", answer: "Shift-Option-Down Arrow will duplicate the line the cursor is on.", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_shift, key_left_alt, key, key_down", description: "This shortcut duplicates the line you are on. On Shift-Option-Down arrow, the cursor will be moved to the duplicated line. Impressive when coding during a job interview.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine every time you hit the down arrow, you shift into a different animal.", gif_url: nil, b_color: nil},
    {question: "When writing code, how do I see suggested code actions like refactor?", answer: "Command-space", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_cmd, key_period", description: "VS Code highlights JavaScript and TypeScript opportunities to refactor code with a lightbulb icon. Command-period will show you available refactoring options. Extensions exist for other languages too: Google \"VS Code refactoring x\", where x is your preferred programming language.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine turning on an off the lights in your office every time you type a period.", gif_url: nil, b_color: nil},
    {question: "How do I see the problems VS Code detects in my code?", answer: "Shift-Command-M will open the Problems panel, where VS Code lists places in the current workspace or project where it detects errors in your code.", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_shift, key_left_cmd, key_m", description: "VS Code, depending on which extensions and linters you have, will offer corrections to code it thinks is incorrect. It's usually right.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Think of a monkey standing behind you watching you code and every time you hit the command key, it squawks at you and jumps up and down.", gif_url: nil, b_color: nil},
    {question: "How do instantly create a second instance of the file I'm editing?", answer: "Command-backslash will open a new code editor to the right of the current editor, with another instance of the file you are in. Very handy when you need to see two parts of the code in the file at the same time. Command-w closes the current editor.", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_cmd, key_pipe", description: "You can open quickly open another code editor panel with command-backslash, look up a need bit of code, and close the second pane with command-w, returning to your main panel without losing your place in the code. A power shortcut!", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine you're walking down a street and you have super-advanced AR glasses that every time you tap the backslash button on the left side shows you a balloon callout above each person's head with their darkest secret.", gif_url: nil, b_color: nil},
    {question: "How do drop the last selected text when I do multiple cursors?", answer: "It's easy to over-select parts of code in VS Studio Code. Command-U will unselect the last bit of text you over-selected.", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_cmd, key_u", description: "So want to change a number of instances in your code, but you over-select. Command-U is Undo for just the cursor.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine being commanded to make a U-turn every time you hear the word \"select\" in what you typically listen to while driving.", gif_url: nil, b_color: nil},
    {question: "How do I select all of the examples of a particular word or name in a file?", answer: "Shift-Command-L will select and create a cursor after every single example of the text that was selected. A definite power Shortcut!", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_shift, key_left_cmd, key_l", description: "Select a chunk of text once, hit shift-Command-L, and all occurrences of that text will be selected and each has a cursor at the end of the selection. A power shortcut.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine being able to command everyone at a party to stand on their left leg. Then imagine they all are now standing on a blinking eraser pad that can make them disappear.", gif_url: nil, b_color: nil},
    {question: "How do I jump to the end of the line of code?", answer: "Most Mac keyboards lack dedicated \"Home\" and \"End\" keys, so you want to edit your keybindings to set workbench.action.terminal.moveToLineEnd to Command-Left Arrow.", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_cmd, key_right", description: "You'll need to change the default keybinding for workbench.action.terminal.moveToLineEnd to Command-left arrow to get this to work, but given the hundreds of times you have to manually move the cursor to the end of a line, it's worth it.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine commanding a rocket that moves you a thousand miles to your left instantly.", gif_url: nil, b_color: nil},
    {question: "How do I quickly hide and show the Sidebar?", answer: "Command-B does the job", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_cmd, key_b", description: "Command-B hides the Sidebar so you have more room for you code.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine you could command a bartender to make you a drink anywhere, anytime.", gif_url: nil, b_color: "#004445"},
    {question: "How do I quickly show the file Explorer?", answer: "Shift-Command-E will show you all the files in your current workspace", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_shift, key_left_cmd, key-e", description: "VS Code uses the sidebar for lots of panes: search, git, extensions. Sometimes, you just want to see the Explorer Pane with all your project's files.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine commanding a Explorer - dressed for a tropical rainforest, complete with pith helmet - that sits on your desk and instantly grabs Exactly what you need off a shelf.", gif_url: nil, b_color: nil},
    {question: "How do I quickly open a Terminal window within VS Code?", answer: "Control-tilde (the ~ key) opens a full Bash session in a Terminal Panel in VS Code, with the present working directory being where the project files are. ", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_ctrl, key_accent", description: "This shortcut opens a full-blown Terminal window, cutting down the number of apps and windows you need to bounce between.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine you were controlling your computer by shaking salt and pepper and other spices on it.", gif_url: nil, b_color: nil},
  ])

  # end
  end_time = Time.now
  duration = (start_time - end_time) / 1.minute
  puts "**************************"
  puts "Task finished at #{end_time} and took #{duration} minutes."
  puts "**************************"
  log.info "Task finished at #{end_time} and took #{duration} minutes."
  log.close
end
