desc "Create Set id: 8, 02/09/2019."
task createset9: :environment do
  log = ActiveSupport::Logger.new("log/create_set_9.log")
  start_time = Time.now
  puts "**************************"
  puts "Create Set and Cards:Atom Shortcuts and Tricks"
  puts "**************************"
  # constants
  # find and kill old cluster cards
  # and the cluster's cards. get ready to update scoreclusters if there is a cluster1
  cheatsheet1 = Cheatsheet.where(display_name: "Atom Shortcuts and Tricks").first
  if cheatsheet1
    old_cheatsheet_id = cheatsheet1.id
    puts "old cheatsheet id was: #{old_cheatsheet_id}"
    cheatsheet1.destroy
    # temp_scoreclusters = Scorecluster.where(cluster_id: old_cluster_id)
    # temp_scorecards = Scorecard.where(cluster_id: old_cluster_id)
  end
  # create new cheatsheet, and add cards back to it.
  test_cheatsheet = Cheatsheet.create!(display_name: "Atom Shortcuts and Tricks", image: "atom-dss.png",
                                 description: "The dozen or so most useful keyboard shortcuts for Atom on the Mac.",
                                 level: "Basic", card_count: -1, Topic: "Atom", os: "")

  # if test_cheatsheet
  #   puts "Affected Scoreclusters: #{test_cheatsheet.count}"
  #   puts "Scoreclusters were found, so update from #{old_cheatsheet_id} to #{test_cheatsheet.id}"
  #   test_cheatsheet.update_all(cluster_id: test_cheatsheet.id)
  # end

  # if temp_scorecards
  #   puts "Affected Scorecards: #{temp_scorecards.count}"
  #   puts "Scorecards were found, so update from #{old_cluster_id} to #{test_cluster.id}"
  #   temp_scorecards.update_all(cluster_id: test_cluster.id)
  # end

  # change cluster_id: x to cluster_id: test_cluster.id
  Card.create!([
    {question: "How do I open the Command Palette?", answer: "shift-cmd-p", citation_title: "atom-keyboard-shortcuts", citation_url: "https://github.com/nwinkler/atom-keyboard-shortcuts", keycaps: "key_left_shift, key_left_cmd, key_p", description: "The Command Palette is your gateway to all Atom commands.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Image getting an enormous paint palette with hundreds of your favorite colors to appear whenever you command it.", gif_url: nil, b_color: nil},
    {question: "How do you open a URL in a file?", answer: "Control-shift-o opens a url if you have selected it in a file", citation_title: "atom-keyboard-shortcuts", citation_url: "https://github.com/nwinkler/atom-keyboard-shortcuts", keycaps: "key_right_ctrl, key_left_shift, key_o", description: "Opens in your default browser the selected URL.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine a tomato shifting into a computer showing a URL.", gif_url: nil, b_color: nil},
    {question: "How do I toggle the File Tree Pane?", answer: "Command-\\ hides/shows the file tree pane for your current project.", citation_title: "atom-keyboard-shortcuts", citation_url: "https://github.com/nwinkler/atom-keyboard-shortcuts", keycaps: "key_left_cmd, key_pipe", description: "Hide or Shows the Tree View of your project.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine growing a huge tree when you plant a tiny seed using a backslash instead of a spade.", gif_url: nil, b_color: nil},
    {question: "How do I duplicate a line of text?", answer: "Shift-command-d will generate a duplicate line of whatever line the cursor is on.", citation_title: "atom-keyboard-shortcuts", citation_url: "https://github.com/nwinkler/atom-keyboard-shortcuts", keycaps: "key_left_cmd, key_left_shift, key_d", description: "Duplicates whatever line the cursor is on in the active file.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine commanding the Devil to jump up and type a duplicate of the line you are on.", gif_url: nil, b_color: nil},
    {question: "How do I open files?", answer: "Open the Fuzzy File Finder", citation_title: "atom-keyboard-shortcuts", citation_url: "https://github.com/nwinkler/atom-keyboard-shortcuts", keycaps: "key_left_cmd, key_t", description: "Opens the File finder which quickly matches file names", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine a picking out a single file with a tiny tweezers.", gif_url: nil, b_color: nil},
    {question: "How do you move among open files/tabs?", answer: "alt-cmd-left arrow, alt-cmd-right arrow", citation_title: "atom-keyboard-shortcuts", citation_url: "https://github.com/nwinkler/atom-keyboard-shortcuts", keycaps: "key_left_cmd, key_left_alt, key_right, or, key_left", description: "Lets you cycle forwards and back through open file tabs", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine commanding an bicycle with arrow keys instead of a handlebar", gif_url: nil, b_color: nil},
    {question: "What if I select too many instances and want to unselect the last one?", answer: "Command U will unselect the last instance selected with Command D", citation_title: "12 Favorite Atom Tips and Shortcuts to Improve Your Workflow", citation_url: "https://www.sitepoint.com/12-favorite-atom-tips-and-shortcuts-to-improve-your-workflow/", keycaps: "key_right_cmd, key_u", description: "It's easy to get carried away selecting with Command D. Command U lets you roll back your selections.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine you are driving and every time you say \"You\" you do an immediate u-turn in traffic.", gif_url: nil, b_color: nil},
    {question: "How do I make multiple selections of a given word or words in the active file?", answer: "Select text, hit Command-d and the next occurrence of your first selection will be selected. You are working with multiple cursors!", citation_title: "atom-keyboard-shortcuts", citation_url: "https://github.com/nwinkler/atom-keyboard-shortcuts", keycaps: "key_right_cmd, key_d", description: "Multiple cursors make changing multiple instances of a word or phrase easy.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine each time you command the Devil he give you a bag of gold.", gif_url: nil, b_color: nil},
    {question: "How do I know what key bindings Atom is set to resolve to?", answer: "Command and . will show what keybindings are in effect for the active file.", citation_title: "atom-keyboard-shortcuts", citation_url: "https://github.com/nwinkler/atom-keyboard-shortcuts", keycaps: "key_left_cmd, key_period", description: "Atom's autocomplete feature depends of which keybindings are in effect at that moment in that file. This command shows you which keybindings are present.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine commanding an giant telescope to focus on a single period of text.", gif_url: nil, b_color: nil},
    {question: "How do I jump to the end of a line of code?", answer: "Command Right Arrow will move the cursor to the end of the line.", citation_title: "Atom Flight Manual - Moving in Atom section", citation_url: "https://flight-manual.atom.io/using-atom/sections/moving-in-atom/", keycaps: "key_left_cmd, key_right", description: "This one shortcut will save you a lot of time and make you a power coder!", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine you are on a roller coaster ride and hitting command-right arrow makes you rocket to the end of the ride.", gif_url: nil, b_color: nil},
    {question: "How do I quickly comment or uncomment code?", answer: "Command slash will comment/uncomment the code using the correct syntax for the current file (HTML, JS, Ruby, etc.)", citation_title: "12 Favorite Atom Tips and Shortcuts to Improve Your Workflow", citation_url: "https://www.sitepoint.com/12-favorite-atom-tips-and-shortcuts-to-improve-your-workflow/", keycaps: "key_left_cmd, key_forward_slash", description: "Being able to say select all your console.log statements and comment them out with a single Command-/ is a great timesaver.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine a pirate slashing at your code with a saber that looks a lot like a slash key.", gif_url: nil, b_color: nil},
    {question: "How do I auto-indent code I just pasted into a file?", answer: "Open the Command Palette, type \"eai\" and the Editor:Auto Indent command will be selected. Then hit return.", citation_title: "12 Favorite Atom Tips and Shortcuts to Improve Your Workflow", citation_url: "https://www.sitepoint.com/12-favorite-atom-tips-and-shortcuts-to-improve-your-workflow/", keycaps: "key_left_shift, key_left_cmd, key_p, then, key_e, key_a, key_i, key_enter", description: "Manually correcting indentation is a pain. learning how to get Atom to do it will save you a lot of time as you code.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.34", mnemonic: "Imagine commanding the Command Palette to appear, and telling it to eat itself while auto-indenting the selected text for you.", gif_url: nil, b_color: nil},
    {question: "How do I trigger autocomplete when I'm typing?", answer: " Do a Control-space to see VS Code's autocomplete options.", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_ctrl, key_space", description: "If you want to see VS Code's detected list of options at a given point in your code again, put the cursor there and hit Control-space.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine controlling a tiny spaceship that can fly around the lines of code you are writing.", gif_url: nil, b_color: nil},
    {question: "Open any File in your project?", answer: "Open the Quick Open Pane", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_cmd, key_p", description: "Opens the Quick Open Pane. Can fuzzy match to open any file in your project, but can also find symbols and run commands.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "VS Code Power Shortcuts", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine an assistant you can command anytime to open anything you want.", gif_url: nil, b_color: nil},
    {question: "How do I go to the Definition of a Function?", answer: "Hit F12 on the top row of your keyboard. If you've set your Mac to use function keys for various system shortcuts, hit key", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_function12", description: "This will jump you to the part of your code that defines the function you have selected.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine jumping around on a giant keyboard to make music, and each time you jump on the F12 key it plays a trumpet.", gif_url: nil, b_color: nil},
    {question: "How do I toggle commenting on and off?", answer: "Command-forward slash will change the line or block of code into a comment, respecting what kind of file you are working in. Command-forward slash will also uncomment a line or block of code.", citation_title: "Visual Studio Code Keyboard shortcuts for macOS", citation_url: "https://code.visualstudio.com/shortcuts/keyboard-shortcuts-macos.pdf", keycaps: "key_left_cmd, command_forward_slash", description: "Learn this one shortcut and you will be able to comment/uncomment code in any file, regardless of type.", cheatsheet_id: test_cheatsheet.id, os: "Mac", answer_type: nil, answer_data: nil, cheatsheet_display_name: "Atom Shortcuts and Tricks", is_sample: false, interface: 1, notes: "1.32.1", mnemonic: "Imagine every time you command a block of text to be commented, it asked you a question.", gif_url: nil, b_color: nil},
  ])

  # end
  end_time = Time.now
  duration = (start_time - end_time) / 1.minute
  puts "**************************"
  puts "Task finished at #{end_time} and took #{duration} minutes."
  puts "**************************"
  log.info "Task finished at #{end_time} and took #{duration} minutes."
  log.close
end
